create table admin_accounts (
    id uuid not null,
    username varchar(100) not null unique,
    password_hash varchar(100) not null,
    enabled boolean not null,
    created_at timestamp with time zone not null,
    primary key (id)
);

create table admin_sessions (
    token varchar(64) not null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    primary key (token)
);

create table questions (
    id bigint generated by default as identity,
    code varchar(255) not null unique,
    display_number integer not null,
    user_group varchar(255) not null,
    type varchar(255) not null,
    prompt_key varchar(255) not null,
    required boolean not null,
    primary key (id)
);

create table question_options (
    id bigint generated by default as identity,
    option_key varchar(255),
    display_order integer not null,
    allows_free_text boolean not null,
    question_id bigint not null,
    primary key (id),
    foreign key (question_id) references questions(id) on delete cascade
);

create table survey_links (
    id uuid not null,
    token varchar(64) not null unique,
    user_group varchar(255) not null,
    created_at timestamp with time zone not null,
    expires_at timestamp with time zone not null,
    consumed_at timestamp with time zone,
    primary key (id)
);

create table survey_responses (
    id uuid not null,
    user_group varchar(255),
    locale varchar(255),
    submitted_at timestamp with time zone,
    primary key (id)
);

create table survey_answers (
    id bigint generated by default as identity,
    single_value varchar(255),
    multi_value_json varchar(255),
    text_value varchar(255),
    other_value varchar(255),
    question_id bigint not null,
    response_id uuid not null,
    primary key (id),
    constraint uk_response_question unique (response_id, question_id),
    foreign key (question_id) references questions(id),
    foreign key (response_id) references survey_responses(id) on delete cascade
);

create index idx_survey_links_token on survey_links(token);
create index idx_survey_answers_response on survey_answers(response_id);
